# array 예제들

array랑 array가 요소의 수가 같으면 서로 더하거나 빼거나 곱하거나... 할 수 있다

___
# 실습 설명

엔화(¥)로 저장한 매출 데이터를 원화(₩)로 변환하는 작업이 필요합니다.

 엔화 매출이 담겨 있는 파이썬 리스트가 주어졌습니다. 
 
 1엔에 10.08원이라고 가정하고, 원화 매출이 담긴 numpy array를 만들어 출력해 주세요.

In [1]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

revenue = np.array(revenue_in_yen)
won_array = revenue * 10.08
won_array

array([3024000., 3427200., 3225600., 3628800., 4435200., 1411200.,
       1814400., 3427200., 3326400., 2923200., 2822400., 3830400.,
       1713600., 1411200., 2318400., 3931200., 4032000., 3528000.,
       3830400., 1512000., 1108800., 2419200., 3830400., 3830400.,
       3427200., 4233600., 1512000., 1310400., 3628800., 3225600.,
       2520000.])

array를 만드는 방법은 파이썬 리스트를 그냥 소괄호 안에 넣는 것이다

그리고 왠지 모르겠지만 array를 만든 그 줄에 곱셈 연산자가지 넣으면 처리를 못한다

따로 넣어줘야 하나보다

___
# 실습 설명

각 지점의 매출을 원화로 변환시키고 더해야 하죠. 

1엔에 10.08원, 1달러에 1138원이라고 가정하세요. 

그리고 두 지점의 매출의 합이 원화로 담긴 numpy array를 만들어 출력해주세요.

In [2]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

revenue_in_dollar = [
    1200, 1600, 1400, 1300, 
    2100, 1400, 1500, 2100, 
    1500, 1500, 2300, 2100, 
    2800, 2600, 1700, 1400, 
    2100, 2300, 1600, 1800, 
    2200, 2400, 2100, 2800, 
    1900, 2100, 1800, 2200, 
    2100, 1600, 1800
]

yen_to = np.array(revenue_in_yen) 
dollar_to = np.array(revenue_in_dollar)
yen_to_won = yen_to * 10.08
dollar_to_won = dollar_to * 1138

won_array = yen_to_won + dollar_to_won

won_array

array([4389600., 5248000., 4818800., 5108200., 6825000., 3004400.,
       3521400., 5817000., 5033400., 4630200., 5439800., 6220200.,
       4900000., 4370000., 4253000., 5524400., 6421800., 6145400.,
       5651200., 3560400., 3612400., 5150400., 6220200., 7016800.,
       5589400., 6623400., 3560400., 3814000., 6018600., 5046400.,
       4568400.])

아 솔직히 리스트,사전,어레이 전부 다 지금 머리속에서 희미한데

그냥 앞으로 계속 가야겠다. 어차피 익숙해져야하는 영역인거 같으니

___
# numpy array 불린 연산

In [5]:
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array1 > 6

array([False, False, False, False, False, False,  True,  True,  True,
        True])

array에는 불린 값도 들어갈수가 있다

In [6]:
array_boolean = np.array([True, False, True, True, True])

np.where()이라는 것도 있다 이것은 괄호 안에 해당하는 인덱스를 리턴한다

In [7]:
index_array = np.where(array_boolean == True)

(array([0, 2, 3, 4], dtype=int64),)

이거로 인덱스 array를 만들고 그걸 원래 array에 대괄호 후 넣어주면 그 인덱스의 값만 튀어나온다

In [9]:
index_array = np.where(array_boolean == True)
array_boolean[index_array]

array([ True,  True,  True,  True])

___
# 실습 설명

성공적이지 않은 날의 매출만 골라서 보고 싶습니다. 20만 엔 이하의 매출만 담긴 numpy array를 출력해주세요.

In [11]:
import numpy as np

revenue = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

revenue_in_yen = np.array(revenue)
bad_days = np.where(revenue_in_yen < 200000)
bad_days_revenue = revenue_in_yen[bad_days]
bad_days_revenue

array([140000, 180000, 170000, 140000, 150000, 110000, 150000, 130000])

자꾸 까먹는데 리스트 자체로는 못 쓴다. 한번 다시 array로 담아줘야 한다

이름을 

*_list*

*_array*

이런식으로 붙여줘서 구분해야겠다

___
# array랑 list

* list는 그냥 값을 추가하거나 제거할 때 사용하면 좋다
* array는 복잡한 계산, 행렬같은 다차원의 배열일 경우에 사용하면 좋다

___
# numpy 기본 통계

In [3]:
import numpy as np
array = np.array([2, 30, 73, 12, 93, 5, 55])
print(array.min())
print(array.max())
print(array.mean())
print(array.std())
print(array.var())
print(np.median(array))

2
93
38.57142857142857
33.08369103115458
1094.5306122448978
30.0


위에서 부터 순서대로

*최소값*

*최대값*

*평균*

*표준편차*

*분산*

*중앙값*

이다